"""Artist-facing platform dictionary and post-bake rules."""

RUNTIME_NAMES = (
    ('StartPosition — Empty, exactly one',
     'On the floor; +Y faces forward; rotate only around Z.'),
    ('Navmesh* — mesh, required', 'Walkable floor and teleport destinations.'),
    ('Probe_<Name> — camera in the probe collection, at least one',
     'Exports as Empty; position only; matching EXR in every look.'),
    ('Skybox[_<Zone>][_<Look>] — mesh, every look',
     'Origin at sky centre; a default sky is required for each look.'),
    ('Zone_<Name> — box mesh; SkyPoint_<Zone> — Empty',
     'Zone includes the floor; Z rotation only. SkyPoint moves sky centre.'),
    ('Hotspot_<Name> — Empty',
     'Floor position, +Y forward; title/order; hotspots/<EmptyName>.jpg.'),
    ('InfoButton_<Name> + InfoPanel_<Name> — Empties',
     'Button/panel positions and rotations; info/<Name>.md.'),
    ('SFX_<Name> — Empty',
     'Positioned sound; Sphere size1, scale = radius; volume/title.'),
    ('Ambience_<Name> — Empty',
     'Position selects zone; Z rotation = recording forward; volume/title.'),
    ('Music_Source / Music_Button / Music_Panel — Empties',
     'Sound source / UI positions; source volume and zone from position.'),
    ('Video_<Name> — mesh',
     'video/<Name>.mov or .mp4; authored UV and material opacity.'),
    ('Clock_<Name> — mesh',
     'First UV spans 0–1 without inversion; digit colour = Base Color.'),
    ('Collision* — mesh', 'Invisible sound collision data.'),
    ('Inspect_<Name> — Empty',
     'Object centre; requires inspect/<Name>.usdz and <Name>.md.'),
    ('RK_<Shader> — material on a Runtime mesh',
     'Uses the app shader library (e.g. RK_Water); object name is free.'),
    ('Teleport* / <Prefix>_StartPosition', 'Reserved for web/iOS; keep them.'),
)

AFTER_BAKE = (
    ('Rebake the whole unit in every lighting look', (
        'Geometry, modifiers, UV, position, rotation or scale changed.',
        'Baked material changed; PBR Diffuse Only mode changed.',
        'Add a member: pack SimpleBake for the whole unit together.',
        'Move a member: repack/rebake both affected units.',
        'Ctrl+J sources: repack result; rebake the unit it came from too.',
        'P split / duplicate: assign the new source to a unit, pack, bake.',
        'Delete: export omits it; shared atlas rebake is optional.',
        'Remove Empty Units when the old unit has no members.',
    )),
    ('No rebake needed', (
        'Rename source objects, meshes or materials; change layer order.',
        'Unit output resolution: lower, or raise up to the baked size.',
        'Visibility: export uses assignments, not outliner visibility.',
        'Source title/order/volume/opacity/brightness/emissiveIntensity:',
        're-export the affected layers; current source values are used.',
        'Glass / Emissive / Runtime original changes: re-export.',
    )),
    ('Lighting and order of work', (
        'Changed lights/occluders: rebake affected units in that look + probes.',
        'Edit originals -> pack SimpleBake -> Setup membership -> queue.',
        'Choose every affected look -> bake -> export layer in each look.',
        'Layer rename: re-export; old files leave the export description.',
        'Old USDZ files remain on disk; optional manual cleanup.',
    )),
    ('Keep managed data intact', (
        'Do not edit PMVR_GENERATED / PMVR_WORK or join their copies.',
        'Keep UV names: first UVMap, second SimpleBake.',
        'Ready is a stored bake result, not an automatic change detector.',
    )),
)
